### ISSUE TITLE
Jenkspy fails "because it is not a valid package"

### ISSUE THREAD

**Issue by cameronclans** [pulquero/agile-powerwall#4]
Hi Mark,

```txt
2024-01-30 18:59:01.577 DEBUG (SyncWorker_4) [custom_components.pyscript] Ignoring 'git+https://github.com/pulquero/jenkspy' because it is not a valid package
...
2024-01-30 18:59:01.693 ERROR (MainThread) [custom_components.pyscript.modules.powerwall_tariff] Exception in </config/pyscript/modules/powerwall_tariff.py> line 3:
import jenkspy
^
ModuleNotFoundError: No module named 'jenkspy'
```
I tried a couple of basic things just to test (like specifying the branch) but no luck. 

FYI - this is within a home assistant docker container running Alpine

**Comment by cameronclans** [comment]
I don't know how valid this approach would be (so I'm not saying it's a problem) but I did also try to pip install using the same :

''' txt
Collecting git+https://github.com/pulquero/jenkspy
  Cloning https://github.com/pulquero/jenkspy to /tmp/pip-req-build-1c6awkep
  Running command git clone --filter=blob:none --quiet https://github.com/pulquero/jenkspy /tmp/pip-req-build-1c6awkep
  Resolved https://github.com/pulquero/jenkspy to commit 87f75af7f3d1e6ba88d8ca554d318a263f002f66
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/site-packages (from jenkspy==0.4.0) (1.26.0)
Building wheels for collected packages: jenkspy
  Building wheel for jenkspy (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [42 lines of output]
      /usr/local/lib/python3.11/site-packages/setuptools/command/build_py.py:204: _Warning: Package 'jenkspy.src' is absent from the `packages` configuration.
      !!
      
              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'jenkspy.src' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.
      
              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'jenkspy.src' is explicitly added
              to the `packages` configuration field.
      
              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).
      
              You can read more about "package discovery" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
      
              If you don't want 'jenkspy.src' to be distributed and are
              already explicitly excluding 'jenkspy.src' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.
      
              You can read more about "package data files" on setuptools documentation page:
      
              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
      
      
              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************
      
      !!
        check.warn(importable)
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for jenkspy
  Running setup.py clean for jenkspy
Failed to build jenkspy
ERROR: Could not build wheels for jenkspy, which is required to install pyproject.toml-based projects
```

**Comment by cameronclans** [comment]
Installed via pip - this suggests (I think) that the package is ok?

```txt
pip install git+https://github.com/pulquero/jenkspy
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting git+https://github.com/pulquero/jenkspy
  Cloning https://github.com/pulquero/jenkspy to /tmp/pip-req-build-zks6xrn4
  Running command git clone --filter=blob:none --quiet https://github.com/pulquero/jenkspy /tmp/pip-req-build-zks6xrn4
  Resolved https://github.com/pulquero/jenkspy to commit 87f75af7f3d1e6ba88d8ca554d318a263f002f66
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.11/site-packages (from jenkspy==0.4.0) (1.26.0)
Building wheels for collected packages: jenkspy
  Building wheel for jenkspy (setup.py) ... done
  Created wheel for jenkspy: filename=jenkspy-0.4.0-cp311-cp311-linux_x86_64.whl size=662624 sha256=639a8d4c91a0554af87484c40d94a2049f42dc4ff5fe71ebbebc1df699f37e99
  Stored in directory: /tmp/pip-ephem-wheel-cache-t0d6ep6g/wheels/7f/07/88/78aae3e5e605b82cea925fd1a351d24bbe7f296ed1f8429ab8
Successfully built jenkspy
Installing collected packages: jenkspy
Successfully installed jenkspy-0.4.0
```

**Comment by pulquero** [comment]
Well done for getting this far! You've basically gone through the same steps as I had to initially get it working. If you look in /usr/local/lib/python3.11/site-packages/jenkspy there should be a jenks.XXXXXXX.so file. If you can attach it to this ticket, I can add it to the jenkspy distribution.

**Comment by cameronclans** [comment]
Google was my friend! I realised that pip install should work but that failed, I found an error re building and figured out that gcc was not installed in the container, did that and the build worked. 

I had 3 jenks.XXXXXXX.so files but only one was executable so I have added that one (jenks.cpython-311-x86_64-linux-musl.so)
[jenks.cpython-311-x86_64-linux-musl.so.zip](https://github.com/pulquero/agile-powerwall/files/14104161/jenks.cpython-311-x86_64-linux-musl.so.zip)

**Comment by pulquero** [comment]
Added, if you pip uninstall jenkspy, you should now find that agile-powerwall can install the dependency by itself.

**Comment by cameronclans** [comment]
Did you update any files or is the dependency resolved in some other way?

**Comment by pulquero** [comment]
No files, it should have fetched the required files from my jenkspy github repo. You might need to manually install it for now while I investigate. It seemed to work on my rpi. I'll see if I can reproduce your setup.

**Comment by cameronclans** [comment]
OK thanks - in which case that didn't work, happy to try anything - one thing I haven't done is test whether a git+https is functioning within the container...I can't see why it wouldn't be as DNS etc works fine as per the other HA installs but I can give it a test with a hello world or similar. 

I've manually installed via pip and excluded from watchtower as gcc and jenkspy get removed if the container updates otherwise.

**Comment by pulquero** [comment]
So, I think I've got a solution now. Essentially, I've pre-packaged jenkspy in a zip, side-stepping pip. For convenience now, you can just download the latest zip from https://github.com/pulquero/agile-powerwall/releases and unzip it in your config directory (doesn't overwrite pyscript.yaml config).

**Comment by cameronclans** [comment]
Great, thank you. I was a little slow testing this but have just finished and everything is looking good. 
Thanks again and have a great weekend!
